### PR TITLE
Fixed CE within Federated Authentication

### PR DESCRIPTION
**Pull request by kimcu-on-thenet**
### New Feature Submissions:

1. A new module - Sitecore.HabitatHome.Foundation.CreativeExchange has been introduced under Foundation layer that makes the Creative Exchange feature export the site or even single page correctly.
2. This is a fix of Issue #39

### CODE REVIEW

**Comment by ezlateva** [comment]
@kimcu-on-thenet This is a great catch! Have you reported this to Sitecore support? It looks like something that would be beneficial to add in SXA

**Comment by kimcu-on-thenet** [comment]
Not yet @ezlateva. Yup, it should be in SXA. Could you please let me know how can I report this bug? Thanks.

**Comment by jeanfrancoislarente** [comment]
@kimcu-on-thenet I'll take care of it internally. Thanks!

**Comment by ezlateva** [comment]
Awesome! Assuming @jeanfrancoislarente will report this and it might get fixed in a next product release, it would still be great to patch the demo

I see that the fix is actually within these lines of the `GetCookieContainer` method
```
   if (cookies.AllKeys.Any(x => x == ".AspNet.Cookies"))
                {
                    cookies.TransferCookie(".AspNet.Cookies", host, container);
                }
```
My only feedback here is maybe instead of overwriting the whole `PageRequestService.cs` we could make it a bit more obvious as to what's being patched by inheriting SXA's service and overwriting just the method

**Comment by jeanfrancoislarente** [comment]
Hey @kimcu-on-thenet  - are you you able to apply @ezlateva's suggestions to your PR?

**Comment by jeanfrancoislarente** [comment]
Also note this bug has been reported to the SXA team and will be fixed in 1.8

**Comment by kimcu-on-thenet** [comment]
@jeanfrancoislarente
I've just updated the PR with the change to make more concise as @ezlateva's suggestions.

Thanks @ezlateva  for your review and suggestion.
Also thanks @jeanfrancoislarente  for reporting this bug to SXA team.
Cheer!

**Pull request merged**
