### PR TITLE
Enhance Data Protection

### PR DESCRIPTION
**Pull request by chorpo**
Move functionality to delete account and export data to separate controller actions;
Enhanced export data functionality;
Add tracking delete account goal

### CODE REVIEW

**Comment by scottmulligan** [comment]
Hi @chorpo. Thanks for the PR!

Can you double check one thing for me please? I deployed your PR and all is looking good except I am unable to click the "Export Data" and "Delete Account" menu items on https://habitathome.dev.local/en/accountmanagement.

I would expect to see new items added under the following location for the new pages: /sitecore/content/Habitat Sites/Habitat Home/home/accountmanagement

I see those menu items listed under here (/sitecore/content/Habitat Sites/Habitat Home/Data/Link Lists/Account Management/Side Navigation) but they link to pages that are missing.

If you still have the following 2 page items, can you add them to the PR? Thanks!

- {F8BB107D-38AF-4C64-9235-3B13F26B01B7}
- {94557F49-05B1-4DA3-8876-F79E86C3630B}

**Comment by chorpo** [comment]
> 
> 
> Hi @chorpo. Thanks for the PR!
> 
> Can you double check one thing for me please? I deployed your PR and all is looking good except I am unable to click the "Export Data" and "Delete Account" menu items on https://habitathome.dev.local/en/accountmanagement.
> 
> I would expect to see new items added under the following location for the new pages: /sitecore/content/Habitat Sites/Habitat Home/home/accountmanagement
> 
> I see those menu items listed under here (/sitecore/content/Habitat Sites/Habitat Home/Data/Link Lists/Account Management/Side Navigation) but they link to pages that are missing.
> 
> If you still have the following 2 page items, can you add them to the PR? Thanks!
> 
>     * {F8BB107D-38AF-4C64-9235-3B13F26B01B7}
> 
>     * {94557F49-05B1-4DA3-8876-F79E86C3630B}

Hi Scott,

Sorry for that. Somehow these files have been not picked by git as changed.

Pushed latest commit with the missing files.

Please, try once again.

Peter

**Comment by scottmulligan** [comment]
Thanks @chorpo ! Good work on this feature.

I will deploy today and merge in as soon as possible.

Thanks again,
Scott

**Comment by chorpo** [comment]
Thanks @scottmulligan. Peter

**Comment by chorpo** [comment]
Excluded exporting interaction data for now as it makes results too big.
Will implement export as ajax call to overcome these issues.

**Comment by jeanfrancoislarente** [comment]
Hey @chorpo,

Just logging here to keep history:

Create account, export Data: OK
Log out
Log in
Export Data - Request Url too long.

**Pull request merged**
